@plr = player()



@hero = associative_array(
            'name': '§bQ§1u§9i§7c§3k§7s§8i§7l§8v§7e§8r',
            'class': 'quicksilver',
            'sig': 's8+SwI5GaD6E3427AmVm2l4Q5KnAotJ7j/h8jlRMLK5+7xHUZBYFa6dxT++jzyM4sLrrGtV0/JeulbUvFf1au4PH34MdXrsOHJqBcuK9kT0q6QS1tdIz6c49PaNbJTaX5y3o9b5wXeMh038H4T5RNqW10jQEBf6eVItG5MznUVdCgAmUhfVl3ZMbTklSVQ50Spp3xofvjGmOo8jdtAX7FaoOEVbKz1UxMY4DdssOvihDLG3Vt0IebV3u9GAquATQuRk6NQdtUR1ijIqttV9VljuL2FUuI+8C/mTr3JgLyZke9EKt2XA1cfYwcm6rMYY59OUU66rviOmTRojh+t11OLhgsvc7DuLzCMEK+I9hYOHBk/7CxEvguwBoSt2Pzu8GZnRMGo+P9IpoPAhe+6pQPlTfJBBaqS/uixDEcPkPmO7nUOzRCUQBoESdrJarGswOiYQxgAQXvemDPo2HDvV1j97TONaf1GyGXwodIpvx4Qjk4nBpWh+zM22Tki7dRhWca4ttNMboJnnggardogp0fRhEeePxGjxc2ZnJeGBIio+avihy1fs7RcfT6FCn7Rz4E3H/M9WyGm/6ym7t6P2jwUSADojjO0mrwUZKIGZvW3vA4awLZDfLwU50KupUhUUJhhaUsATVC1LtiupvljE2O/0UWH/dGb51JHRyhQZQ3q0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ0MzUwNjgwNDEsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmNhYzhmNTViODQzOGU0ZjI2ZGI4Y2UwNTJhZDFiMmU4OWZkZTNjYmU1ZGFhOTY1YWQ0ZGI2ZDYxZGE5NWUifX19',
            'altskins': array(
                array(  
                    'sig': 'qUEPx94UL8LUrqgKnaY10+81qG4NmzQqnkcJWWslhSS30Qwooc6/c7k4/hTEZ9e1YMcewmkGUim0mPNYFvXW0FvJ6MyK0NGv+uZ6g2DpeIeuKFDLAjQWcau5/HliPUxDR6qZJbfL/ZTNN0Vm5WWIELwIJfIkRcQPV5ARsdCXeF+p6ddz+1TVVfJaJvRJbMiZAvwBDoBZxk36R2Olkj/9JA84/agR2gfdBkvCuij2En8MD8iJVG7mQeam0xXhnl5DgbFnCDp1xFzICiMk6jLtphT6xsn01Vhd9Un8r9ThhAicPNUEPVLGWDcUajZ7iSvF34aGiYUpK41z2emdkK1Wmj9ydW0VRzHaoWB7bO/ZoqFizIMRf7cdf+Y9pcXmWbB5PN12FesA/uWXgh2yu7z9AzFlwgJ1MdU2eClR6w5ZJcHjgTtAGhjpyS2mDySQ5lRIOQk9hLkLMKv/1C7kpeD0NhgdVm13gqrYyVHKZWAUN1cSZzH+2czAagemc3EzanOoel10ZKZeXCfIBBHak7M8RZEFtQ44Ovir9R6Wt9oGo45K9Qnyi1BCCP3sA2bsFCZYiNiFByPTxTS2IvPD96TblS7pTLKmlCRw8gqs2T8U681GBoMTBGDnR8rxkMXJBT0qSDJJ9Y/ZcyxNhJwuf4mBfNhwS9guiqjkT5b+cYlTptw=',                    
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ0MzUwNjgwNDEsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmNhYzhmNTViODQzOGU0ZjI2ZGI4Y2UwNTJhZDFiMmU4OWZkZTNjYmU1ZGFhOTY1YWQ0ZGI2ZDYxZGE5NWUifX19'              
                     )
            ),                
            'trail': '',
            'op': 'false',
            'speech': "I Am Not Ze Fastest Man Alive!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
